# ~/.config/starship.toml

# Inserts a blank line between shell prompts.
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
style = "bold cyan"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = "🌱"
style = "bold purple"

[git_status]
style = "bold red"
stashed = "📦"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "🤷"
staged = '[++\\($count\\)](green)'
modified = "📝"
renamed = "»"
deleted = "✘"

[hostname]
ssh_only = true
format = "on [$hostname](bold yellow) "
disabled = false

[username]
show_always = false
style_user = "bold yellow"

# Disable some language modules by default to keep the prompt clean.
# They can be enabled if needed.
[c]
disabled = true

[dotnet]
disabled = true
